name: PR Checks

on:
  workflow_dispatch:
  pull_request:
    paths:
      - path-finding-visualizer/**
      - .github/**
  push:
    branches:
      - main
    paths:
      - path-finding-visualizer/**
      - .github/**
jobs:
  pr-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd path-finding-visualizer
          npm install
      
      - name: Lint Project
        run: |
          cd path-finding-visualizer 
          npm install
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          npm run lint >> $GITHUB_STEP_SUMMARY